<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-0BBKQ66I" name="Default test" tests="10" failures="1" timestamp="15 Mar 2020 11:22:12 GMT" time="43.621" errors="0">
  <testcase name="all_Tickets" time="10.618" classname="com.DBApiTest.Testcases.Ticketing_Module"/>
  <testcase name="categories" time="1.431" classname="com.DBApiTest.Testcases.Ticketing_Module"/>
  <testcase name="concernedteams" time="1.503" classname="com.DBApiTest.Testcases.Ticketing_Module"/>
  <testcase name="createTicket" time="1.767" classname="com.DBApiTest.Testcases.Ticketing_Module">
    <failure type="java.lang.AssertionError" message="expected [null] but found [APPROVED]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [APPROVED]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:130)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.DBApiTest.Testcases.Ticketing_Module.createTicket(Ticketing_Module.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- createTicket -->
  <testcase name="directreportees" time="1.528" classname="com.DBApiTest.Testcases.Ticketing_Module"/>
  <testcase name="image" time="1.509" classname="com.DBApiTest.Testcases.Ticketing_Module"/>
  <testcase name="indirectreportees" time="1.513" classname="com.DBApiTest.Testcases.Ticketing_Module"/>
  <testcase name="officecodes" time="1.57" classname="com.DBApiTest.Testcases.Ticketing_Module"/>
  <testcase name="raisedTicketbyUser" time="1.444" classname="com.DBApiTest.Testcases.Ticketing_Module"/>
  <testcase name="singleticktet" time="1.454" classname="com.DBApiTest.Testcases.Ticketing_Module"/>
</testsuite> <!-- Default test -->
